# Generated by Django 5.1.2 on 2024-10-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='password',
        ),
    ]
