# Generated by Django 5.1.2 on 2024-11-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='factura',
            field=models.ImageField(blank=True, null=True, upload_to='facturas/'),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
