# Generated by Django 5.1.2 on 2024-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productofavorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0, help_text='Cantidad de veces que se ha vendido el producto'),
        ),
    ]
