# Generated by Django 5.1.2 on 2024-12-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producto_imagen'),
        ('products', '0004_alter_producto_options_producto_ventas'),
    ]

    operations = [
    ]
