--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2024-11-30 18:15:50

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 18478)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 18477)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 18486)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 18485)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 18472)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 18471)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 18737)
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 18717)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 18716)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18464)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18463)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 18456)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18455)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 18750)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 32783)
-- Name: orders_detallepedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_detallepedido (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    producto_id bigint NOT NULL,
    pedido_id bigint NOT NULL
);


ALTER TABLE public.orders_detallepedido OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 32782)
-- Name: orders_detallepedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_detallepedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_detallepedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 254 (class 1259 OID 32769)
-- Name: orders_pedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_pedido (
    id bigint NOT NULL,
    fecha_pedido timestamp with time zone NOT NULL,
    total double precision,
    estado boolean NOT NULL,
    usuario_id bigint NOT NULL,
    factura character varying(100)
);


ALTER TABLE public.orders_pedido OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 32768)
-- Name: orders_pedido_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_pedido ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 24577)
-- Name: products_categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_categoria (
    id bigint NOT NULL,
    nombre_categoria character varying(50) NOT NULL
);


ALTER TABLE public.products_categoria OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 24576)
-- Name: products_categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 24583)
-- Name: products_producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products_producto (
    id bigint NOT NULL,
    nombre_producto character varying(100) NOT NULL,
    descripcion text NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    imagen character varying(100),
    categoria_id bigint NOT NULL,
    vendedor_id bigint NOT NULL
);


ALTER TABLE public.products_producto OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 24582)
-- Name: products_producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products_producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 24613)
-- Name: shopping_car_carrito; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shopping_car_carrito (
    id bigint NOT NULL,
    fecha_creacion timestamp with time zone NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.shopping_car_carrito OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 24612)
-- Name: shopping_car_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shopping_car_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_car_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 252 (class 1259 OID 24619)
-- Name: shopping_car_carritoitem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shopping_car_carritoitem (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    carrito_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.shopping_car_carritoitem OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 24618)
-- Name: shopping_car_carritoitem_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shopping_car_carritoitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_car_carritoitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 18596)
-- Name: users_incluye; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_incluye (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    pedido_id bigint NOT NULL,
    producto_id bigint NOT NULL
);


ALTER TABLE public.users_incluye OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 18595)
-- Name: users_incluye_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_incluye ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_incluye_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 18524)
-- Name: users_metodopago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_metodopago (
    id bigint NOT NULL,
    tipo_pago character varying(50) NOT NULL
);


ALTER TABLE public.users_metodopago OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 18523)
-- Name: users_metodopago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_metodopago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_metodopago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 18574)
-- Name: users_pago; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_pago (
    id bigint NOT NULL,
    monto double precision NOT NULL,
    fecha_pago date NOT NULL,
    metodo_pago_id bigint NOT NULL,
    pedido_id bigint NOT NULL
);


ALTER TABLE public.users_pago OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 18573)
-- Name: users_pago_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_pago ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_pago_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 18530)
-- Name: users_rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_rol (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.users_rol OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 18529)
-- Name: users_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 18538)
-- Name: users_usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    cedula character varying(10) NOT NULL,
    direccion character varying(255) NOT NULL,
    telefono character varying(20) NOT NULL,
    rol_id bigint NOT NULL
);


ALTER TABLE public.users_usuario OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 18550)
-- Name: users_usuario_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_usuario_groups OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 18549)
-- Name: users_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 18537)
-- Name: users_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 18556)
-- Name: users_usuario_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_usuario_user_permissions OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 18555)
-- Name: users_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4807 (class 2606 OID 18515)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4812 (class 2606 OID 18501)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4815 (class 2606 OID 18490)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 18482)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4802 (class 2606 OID 18492)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4804 (class 2606 OID 18476)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4855 (class 2606 OID 18741)
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- TOC entry 4857 (class 2606 OID 18743)
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 4851 (class 2606 OID 18724)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4797 (class 2606 OID 18470)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4799 (class 2606 OID 18468)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4795 (class 2606 OID 18462)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 18756)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4882 (class 2606 OID 32787)
-- Name: orders_detallepedido orders_detallepedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_detallepedido
    ADD CONSTRAINT orders_detallepedido_pkey PRIMARY KEY (id);


--
-- TOC entry 4878 (class 2606 OID 32773)
-- Name: orders_pedido orders_pedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_pedido
    ADD CONSTRAINT orders_pedido_pkey PRIMARY KEY (id);


--
-- TOC entry 4863 (class 2606 OID 24581)
-- Name: products_categoria products_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_categoria
    ADD CONSTRAINT products_categoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 24589)
-- Name: products_producto products_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_producto
    ADD CONSTRAINT products_producto_pkey PRIMARY KEY (id);


--
-- TOC entry 4869 (class 2606 OID 24617)
-- Name: shopping_car_carrito shopping_car_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carrito
    ADD CONSTRAINT shopping_car_carrito_pkey PRIMARY KEY (id);


--
-- TOC entry 4873 (class 2606 OID 24631)
-- Name: shopping_car_carritoitem shopping_car_carritoitem_carrito_id_producto_id_176ec145_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carritoitem
    ADD CONSTRAINT shopping_car_carritoitem_carrito_id_producto_id_176ec145_uniq UNIQUE (carrito_id, producto_id);


--
-- TOC entry 4875 (class 2606 OID 24623)
-- Name: shopping_car_carritoitem shopping_car_carritoitem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carritoitem
    ADD CONSTRAINT shopping_car_carritoitem_pkey PRIMARY KEY (id);


--
-- TOC entry 4847 (class 2606 OID 18600)
-- Name: users_incluye users_incluye_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_incluye
    ADD CONSTRAINT users_incluye_pkey PRIMARY KEY (id);


--
-- TOC entry 4817 (class 2606 OID 18528)
-- Name: users_metodopago users_metodopago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_metodopago
    ADD CONSTRAINT users_metodopago_pkey PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 18578)
-- Name: users_pago users_pago_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_pago
    ADD CONSTRAINT users_pago_pkey PRIMARY KEY (id);


--
-- TOC entry 4819 (class 2606 OID 18536)
-- Name: users_rol users_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_rol
    ADD CONSTRAINT users_rol_pkey PRIMARY KEY (id);


--
-- TOC entry 4822 (class 2606 OID 18548)
-- Name: users_usuario users_usuario_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_cedula_key UNIQUE (cedula);


--
-- TOC entry 4831 (class 2606 OID 18554)
-- Name: users_usuario_groups users_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_groups
    ADD CONSTRAINT users_usuario_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4834 (class 2606 OID 18616)
-- Name: users_usuario_groups users_usuario_groups_usuario_id_group_id_db69fe93_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_groups
    ADD CONSTRAINT users_usuario_groups_usuario_id_group_id_db69fe93_uniq UNIQUE (usuario_id, group_id);


--
-- TOC entry 4824 (class 2606 OID 18544)
-- Name: users_usuario users_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4836 (class 2606 OID 18630)
-- Name: users_usuario_user_permissions users_usuario_user_permi_usuario_id_permission_id_9b373975_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_user_permissions
    ADD CONSTRAINT users_usuario_user_permi_usuario_id_permission_id_9b373975_uniq UNIQUE (usuario_id, permission_id);


--
-- TOC entry 4839 (class 2606 OID 18560)
-- Name: users_usuario_user_permissions users_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_user_permissions
    ADD CONSTRAINT users_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4828 (class 2606 OID 18546)
-- Name: users_usuario users_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_username_key UNIQUE (username);


--
-- TOC entry 4805 (class 1259 OID 18516)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4810 (class 1259 OID 18512)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4813 (class 1259 OID 18513)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4800 (class 1259 OID 18498)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4853 (class 1259 OID 18749)
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- TOC entry 4849 (class 1259 OID 18735)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4852 (class 1259 OID 18736)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4858 (class 1259 OID 18758)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4861 (class 1259 OID 18757)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4880 (class 1259 OID 32818)
-- Name: orders_detallepedido_pedido_id_64edb50c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_detallepedido_pedido_id_64edb50c ON public.orders_detallepedido USING btree (pedido_id);


--
-- TOC entry 4883 (class 1259 OID 32817)
-- Name: orders_detallepedido_producto_id_235a2324; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_detallepedido_producto_id_235a2324 ON public.orders_detallepedido USING btree (producto_id);


--
-- TOC entry 4879 (class 1259 OID 32793)
-- Name: orders_pedido_usuario_id_3727f801; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX orders_pedido_usuario_id_3727f801 ON public.orders_pedido USING btree (usuario_id);


--
-- TOC entry 4864 (class 1259 OID 24600)
-- Name: products_producto_categoria_id_ed491ca4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_producto_categoria_id_ed491ca4 ON public.products_producto USING btree (categoria_id);


--
-- TOC entry 4867 (class 1259 OID 24601)
-- Name: products_producto_vendedor_id_984dbbd1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX products_producto_vendedor_id_984dbbd1 ON public.products_producto USING btree (vendedor_id);


--
-- TOC entry 4870 (class 1259 OID 24629)
-- Name: shopping_car_carrito_usuario_id_7e77f11d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shopping_car_carrito_usuario_id_7e77f11d ON public.shopping_car_carrito USING btree (usuario_id);


--
-- TOC entry 4871 (class 1259 OID 24642)
-- Name: shopping_car_carritoitem_carrito_id_d88d3461; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shopping_car_carritoitem_carrito_id_d88d3461 ON public.shopping_car_carritoitem USING btree (carrito_id);


--
-- TOC entry 4876 (class 1259 OID 24643)
-- Name: shopping_car_carritoitem_producto_id_cfdd9304; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX shopping_car_carritoitem_producto_id_cfdd9304 ON public.shopping_car_carritoitem USING btree (producto_id);


--
-- TOC entry 4845 (class 1259 OID 18702)
-- Name: users_incluye_pedido_id_85baa135; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_incluye_pedido_id_85baa135 ON public.users_incluye USING btree (pedido_id);


--
-- TOC entry 4848 (class 1259 OID 18703)
-- Name: users_incluye_producto_id_4de505fa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_incluye_producto_id_4de505fa ON public.users_incluye USING btree (producto_id);


--
-- TOC entry 4841 (class 1259 OID 18665)
-- Name: users_pago_metodo_pago_id_7c192a34; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_pago_metodo_pago_id_7c192a34 ON public.users_pago USING btree (metodo_pago_id);


--
-- TOC entry 4842 (class 1259 OID 18666)
-- Name: users_pago_pedido_id_f8e64bd1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_pago_pedido_id_f8e64bd1 ON public.users_pago USING btree (pedido_id);


--
-- TOC entry 4820 (class 1259 OID 18613)
-- Name: users_usuario_cedula_db80ec32_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_cedula_db80ec32_like ON public.users_usuario USING btree (cedula varchar_pattern_ops);


--
-- TOC entry 4829 (class 1259 OID 18628)
-- Name: users_usuario_groups_group_id_9d969afd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_groups_group_id_9d969afd ON public.users_usuario_groups USING btree (group_id);


--
-- TOC entry 4832 (class 1259 OID 18627)
-- Name: users_usuario_groups_usuario_id_3a8a9a06; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_groups_usuario_id_3a8a9a06 ON public.users_usuario_groups USING btree (usuario_id);


--
-- TOC entry 4825 (class 1259 OID 18614)
-- Name: users_usuario_rol_id_9bc301ef; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_rol_id_9bc301ef ON public.users_usuario USING btree (rol_id);


--
-- TOC entry 4837 (class 1259 OID 18642)
-- Name: users_usuario_user_permissions_permission_id_bf5f5453; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_user_permissions_permission_id_bf5f5453 ON public.users_usuario_user_permissions USING btree (permission_id);


--
-- TOC entry 4840 (class 1259 OID 18641)
-- Name: users_usuario_user_permissions_usuario_id_75526fda; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_user_permissions_usuario_id_75526fda ON public.users_usuario_user_permissions USING btree (usuario_id);


--
-- TOC entry 4826 (class 1259 OID 18612)
-- Name: users_usuario_username_399a0cac_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_usuario_username_399a0cac_like ON public.users_usuario USING btree (username varchar_pattern_ops);


--
-- TOC entry 4885 (class 2606 OID 18507)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4886 (class 2606 OID 18502)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4884 (class 2606 OID 18493)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4898 (class 2606 OID 18744)
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_users_usuario_id FOREIGN KEY (user_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4896 (class 2606 OID 18725)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4897 (class 2606 OID 18730)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_usuario_id FOREIGN KEY (user_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4905 (class 2606 OID 32812)
-- Name: orders_detallepedido orders_detallepedido_pedido_id_64edb50c_fk_orders_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_detallepedido
    ADD CONSTRAINT orders_detallepedido_pedido_id_64edb50c_fk_orders_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.orders_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4906 (class 2606 OID 32807)
-- Name: orders_detallepedido orders_detallepedido_producto_id_235a2324_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_detallepedido
    ADD CONSTRAINT orders_detallepedido_producto_id_235a2324_fk_products_ FOREIGN KEY (producto_id) REFERENCES public.products_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4904 (class 2606 OID 32788)
-- Name: orders_pedido orders_pedido_usuario_id_3727f801_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_pedido
    ADD CONSTRAINT orders_pedido_usuario_id_3727f801_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4899 (class 2606 OID 24590)
-- Name: products_producto products_producto_categoria_id_ed491ca4_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_producto
    ADD CONSTRAINT products_producto_categoria_id_ed491ca4_fk_products_ FOREIGN KEY (categoria_id) REFERENCES public.products_categoria(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4900 (class 2606 OID 24595)
-- Name: products_producto products_producto_vendedor_id_984dbbd1_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products_producto
    ADD CONSTRAINT products_producto_vendedor_id_984dbbd1_fk_users_usuario_id FOREIGN KEY (vendedor_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4902 (class 2606 OID 24632)
-- Name: shopping_car_carritoitem shopping_car_carrito_carrito_id_d88d3461_fk_shopping_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carritoitem
    ADD CONSTRAINT shopping_car_carrito_carrito_id_d88d3461_fk_shopping_ FOREIGN KEY (carrito_id) REFERENCES public.shopping_car_carrito(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4903 (class 2606 OID 24637)
-- Name: shopping_car_carritoitem shopping_car_carrito_producto_id_cfdd9304_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carritoitem
    ADD CONSTRAINT shopping_car_carrito_producto_id_cfdd9304_fk_products_ FOREIGN KEY (producto_id) REFERENCES public.products_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4901 (class 2606 OID 24624)
-- Name: shopping_car_carrito shopping_car_carrito_usuario_id_7e77f11d_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shopping_car_carrito
    ADD CONSTRAINT shopping_car_carrito_usuario_id_7e77f11d_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4894 (class 2606 OID 32819)
-- Name: users_incluye users_incluye_pedido_id_85baa135_fk_orders_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_incluye
    ADD CONSTRAINT users_incluye_pedido_id_85baa135_fk_orders_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.orders_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4895 (class 2606 OID 24607)
-- Name: users_incluye users_incluye_producto_id_4de505fa_fk_products_producto_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_incluye
    ADD CONSTRAINT users_incluye_producto_id_4de505fa_fk_products_producto_id FOREIGN KEY (producto_id) REFERENCES public.products_producto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4892 (class 2606 OID 18655)
-- Name: users_pago users_pago_metodo_pago_id_7c192a34_fk_users_metodopago_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_pago
    ADD CONSTRAINT users_pago_metodo_pago_id_7c192a34_fk_users_metodopago_id FOREIGN KEY (metodo_pago_id) REFERENCES public.users_metodopago(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4893 (class 2606 OID 32824)
-- Name: users_pago users_pago_pedido_id_f8e64bd1_fk_orders_pedido_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_pago
    ADD CONSTRAINT users_pago_pedido_id_f8e64bd1_fk_orders_pedido_id FOREIGN KEY (pedido_id) REFERENCES public.orders_pedido(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4888 (class 2606 OID 18622)
-- Name: users_usuario_groups users_usuario_groups_group_id_9d969afd_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_groups
    ADD CONSTRAINT users_usuario_groups_group_id_9d969afd_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4889 (class 2606 OID 18617)
-- Name: users_usuario_groups users_usuario_groups_usuario_id_3a8a9a06_fk_users_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_groups
    ADD CONSTRAINT users_usuario_groups_usuario_id_3a8a9a06_fk_users_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4887 (class 2606 OID 18607)
-- Name: users_usuario users_usuario_rol_id_9bc301ef_fk_users_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario
    ADD CONSTRAINT users_usuario_rol_id_9bc301ef_fk_users_rol_id FOREIGN KEY (rol_id) REFERENCES public.users_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4890 (class 2606 OID 18636)
-- Name: users_usuario_user_permissions users_usuario_user_p_permission_id_bf5f5453_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_user_permissions
    ADD CONSTRAINT users_usuario_user_p_permission_id_bf5f5453_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4891 (class 2606 OID 18631)
-- Name: users_usuario_user_permissions users_usuario_user_p_usuario_id_75526fda_fk_users_usu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_usuario_user_permissions
    ADD CONSTRAINT users_usuario_user_p_usuario_id_75526fda_fk_users_usu FOREIGN KEY (usuario_id) REFERENCES public.users_usuario(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-11-30 18:15:50

--
-- PostgreSQL database dump complete
--

