# Generated by Django 5.1.2 on 2024-11-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_producto_categoria_remove_producto_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contiene',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='contiene',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Contiene',
        ),
    ]
